---
- hosts: rancher
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance
      ec2:
        region: us-west-2
        key_name: ubu16.04
        instance_type: t2.micro 
        image: ami-2a9f1352 
        count: 1 
        vpc_subnet_id: subnet-cb5ab0ac
        assign_public_ip: no
        group: default
        volumes: 
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 100
            delete_on_termination: true
 #       instance_tags:
#        Name: "{{ Server_name }}"
